### ISSUE TITLE
Revise Display of Report & Comment Times

### ISSUE THREAD

**Issue by jergagon1** [jergagon1/fuzzface#227]
Revise so that display of dates and times within the last 24 hour period are given in relative times without a date. Check if capability exists in moment.js library currently being used.
"2 hours 15 minutes ago"
Or for < 1 hour ago
"48 minutes ago"
Dates and times outside of last 24 hour period should display as they are currently with day, date and time.

**Comment by zudochkin** [comment]
Can we close it?
