### ISSUE TITLE
Explore Reducing Height of Top Navbar

### ISSUE THREAD

**Issue by jergagon1** [jergagon1/fuzzface#228]
Explore slightly reducing height of top navbar in desktop media queries. Upon approval of styling, adjust any related header elements including notifications list.

**Comment by jergagon1** [comment]
This was merged, however upon closer review I think it was the reverse of what I was thinking - The menu bar should be decreased in height and the notifications moved up accordingly. I think the menu bar was 50px before and was increased to 60px. Let's see what 30 or 40px looks like. You will probably need to recenter the menu items vertically.

**Comment by zudochkin** [comment]
Ok, I see, I will fix it

**Comment by zudochkin** [comment]
![fuzzfinders 2015-11-17 13-56-41](https://cloud.githubusercontent.com/assets/283295/11209597/218493c4-8d33-11e5-98f7-7da3efad082f.png)
![fuzzfinders 2015-11-17 13-55-46](https://cloud.githubusercontent.com/assets/283295/11209596/21841ba6-8d33-11e5-8704-689132592206.png)
40px and 30px correspondingly. Do you like some? @jergagon1

**Comment by jergagon1** [comment]
We like the 30px height version. Thanks
