### ISSUE TITLE
FuzzFile User Profile Page/User profile image

### ISSUE THREAD

**Issue by jergagon1** [jergagon1/fuzzface#237]
1. Add a user profile image
   A. Selecting a profile image will not be required at sign up, but can be uploaded from FuzzFile page
   B. Provide default image if user doesn't provide one
2. Basic Page Styling
3. User can edit their info (username, zipcode, password)

**Comment by jergagon1** [comment]
I've merged in and it looks good. Nice work on the Angular. One thing to check is the zipcode - it wasn't pre-populating from the value I had saved when I created my account. Please review and see if we can get that to show so a user can see their current settings.

**Comment by zudochkin** [comment]
It was my fault. It will be fixed in https://github.com/jergagon1/fuzzface/pull/259
