### ISSUE TITLE
Direct Links to report modals

### ISSUE THREAD

**Issue by jergagon1** [jergagon1/fuzzface#261]
Review and implement direct links to report modals. Modals should include map and full comments section as discussed in previous Issue. User feedback comment.

**Comment by zudochkin** [comment]
- [x] Public link should be something like **/4-found-report-pet-name**
- [x] Read-only access for guest users
- [x] Public link in detail report view
- [x] Public link to a report in comment emails
- [x] Redirect back to that specific link in the full logged in mode

**Comment by zudochkin** [comment]
I think we can close it
